package iso8583

import (
	"context"
	"errors"
	"testing"

	"github.com/Witkas/iso8583/llm"
)

// fakeGenerator returns a canned draft, so Generate can be tested without any
// network or provider.
type fakeGenerator struct {
	draft llm.Draft
	err   error
	// gotCatalog records what Generate handed the generator.
	gotCatalog llm.Catalog
}

func (f *fakeGenerator) Describe(_ context.Context, _ string, cat llm.Catalog) (llm.Draft, error) {
	f.gotCatalog = cat
	return f.draft, f.err
}

func TestGenerateValidDraft(t *testing.T) {
	p := mustDefault(t)
	gen := &fakeGenerator{draft: llm.Draft{
		MTI:    "0100",
		Fields: map[int]string{2: "4111111111111111", 3: "000000", 4: "000000004500", 49: "840"},
	}}

	msg, raw, err := Generate(context.Background(), gen, p, "a $45 purchase")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	// The bytes must be real and re-parseable.
	got, err := Parse(raw, p)
	if err != nil {
		t.Fatalf("re-Parse of generated bytes: %v", err)
	}
	if got.MTI != "0100" || got.Fields[4].Value != "000000004500" {
		t.Errorf("round-trip mismatch: mti=%q amt=%q", got.MTI, got.Fields[4].Value)
	}
	if msg.Fields[2].Value != "4111111111111111" {
		t.Errorf("returned message missing PAN")
	}

	// Generate must have handed the model the packager's field catalog.
	if len(gen.gotCatalog.Fields) == 0 {
		t.Error("catalog passed to generator was empty")
	}
}

func TestGenerateRejectsInvalidDraft(t *testing.T) {
	p := mustDefault(t)
	// Amount field 4 is FIXED at 12; a 4-char value must be rejected by Pack.
	gen := &fakeGenerator{draft: llm.Draft{MTI: "0100", Fields: map[int]string{4: "4500"}}}

	if _, _, err := Generate(context.Background(), gen, p, "bad"); err == nil {
		t.Fatal("expected an error for an invalid model draft")
	}
}

func TestGeneratePropagatesGeneratorError(t *testing.T) {
	p := mustDefault(t)
	gen := &fakeGenerator{err: errors.New("provider unavailable")}

	_, _, err := Generate(context.Background(), gen, p, "x")
	if err == nil || !errors.Is(err, err) {
		t.Fatalf("expected the generator error to surface, got %v", err)
	}
}

func TestGenerateNilGenerator(t *testing.T) {
	p := mustDefault(t)
	if _, _, err := Generate(context.Background(), nil, p, "x"); err == nil {
		t.Fatal("expected error with nil generator")
	}
}
